Improvements
evanlucas/node-review pull request #7
Opened 2017-01-29 10:00 UTC by TimothyGu

Bug fixes:

- #5 
- nodejs/node#10952
- PR URLs with `#` fragments

Also some internal simplifications of RegExps, Promises, Maps, etc.

2017-01-30 11:33 UTC, evanlucas requested changes
Wow, thanks a lot for the contributions! I left a few comments, but overall looks pretty good.

2017-01-30 11:33 UTC, evanlucas commented on review.js
> -  function getFixesUrl() {
was this not used?

2017-01-30 11:33 UTC, evanlucas commented on review.js
> +  function getCollaborators() {
I would prefer to keep the callback here vs returning a promise

2017-01-30 11:33 UTC, evanlucas commented on review.js
> +      if (Array.from(paragraphs).some(p => LGTM_RE.test(p.innerHTML))) {
just curious, what's the reason for this change? I find this a lot more difficult to read than the previous implementation.

2017-01-30 15:53 UTC, TimothyGu commented on review.js
> -  function getFixesUrl() {
No it wasn't.

2017-01-30 15:55 UTC, TimothyGu commented on review.js
> +      if (Array.from(paragraphs).some(p => LGTM_RE.test(p.innerHTML))) {
In https://github.com/nodejs/node/pull/10657, a LGTM embedded in a `<blockquote>` (and therefore one that does not belong to the author of the comment) was recognized. This piece of code only looks for direct `<p>` children of `.comment-body`, and mitigates that issue.

2017-01-30 15:56 UTC, evanlucas commented on review.js
> +      if (Array.from(paragraphs).some(p => LGTM_RE.test(p.innerHTML))) {
ah cool that makes sense.

2017-01-30 15:58 UTC, TimothyGu commented on review.js
> +  function getCollaborators() {
Okay, but I wonder what the reason for this is?

2017-01-31 11:57 UTC, evanlucas commented on review.js
> +  function getCollaborators() {
It is strictly preference. I prefer nodebacks over promises. :]

2017-02-01 17:54 UTC, TimothyGu commented on review.js
> +  function getCollaborators() {
Fixed. PTAL!

2017-02-06 12:01 UTC, evanlucas approved these changes

2017-02-06 12:01 UTC, merged

2017-02-06 12:02 UTC, evanlucas commented
Thanks!